In [1]:
import pandas as pd
import glob
import ssqueezepy #para convertir la señal en imagen
from ssqueezepy import cwt
from ssqueezepy.visuals import plot, imshow
import os
import mne #eeg analysis library
import scipy.io
#import torch.nn as nn
#import torch
import numpy as np
import re
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from tqdm import tqdm

In [5]:
#X = np.load('C:\\Users\\47575909\\Desktop\\X_PCA.npy')
#y = np.load('C:\\Users\\47575909\\Desktop\\y_PCA.npy')

In [3]:
#X.shape

NameError: name 'X' is not defined

In [7]:
#ACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
#PRUEBO CON MENOS DATOS
#ACA SUBO LOS ARCHIVOS DE TFRECORD
TFrecord_directory = 'C:\\Users\\47575909\\Desktop\\data_para_predict' 

#lista de archivos TFRecord en la carpeta
filenames = [os.path.join(TFrecord_directory, f) for f in os.listdir(TFrecord_directory) if f.endswith('.tfrecord')]

#Hago un dataset de TensorFlow a partir de los archivos TFRecord
dataset = tf.data.TFRecordDataset(filenames)

#función para parsear los datos de TFRecord
def parse_tfrecord_fn(example):
    feature_description = {
        'grpno': tf.io.FixedLenFeature([], tf.int64),
        'label': tf.io.FixedLenFeature([], tf.int64),
        'path': tf.io.FixedLenFeature([], tf.string),
    }
    example = tf.io.parse_single_example(example, feature_description)
    return example

parsed_dataset = dataset.map(parse_tfrecord_fn)

#batching para argar los datos en lotes
batch_size = 2  #puedo cambiar el tamaño (en la PC del colegio el máximo es 16, pero capáz que le tengo que poner menos)
batched_dataset = parsed_dataset.batch(batch_size)

In [30]:
#batched_dataset

In [4]:
'''#SEPARO EN X E Y
X = []
y = []

#itero los lotes
for batch_data in batched_dataset:
    paths = batch_data['path'].numpy()
    labels = batch_data['label'].numpy()
    
    #cargo los scaleograms desde los archivos .npy
    batch_X = []
    for path in paths:
        spectrogram = np.load(path.decode('utf-8'))
        batch_X.append(spectrogram)
    
#//////NUEVO

    #primero tengo que convertirlo en un archivo numpy porque sino no quiere
    batch_X = np.array(batch_X)
    
    X_shape = batch_X.shape
    shape_0 = X_shape[0]

    # Aplanar
    batch_X = batch_X.reshape(shape_0, -1)
    
    #NORMALIZO X en rango [-1, 1] para que el cero quede en el centro
    min_val = np.min(batch_X)
    max_val = np.max(batch_X)

    X = -1 + 2 * (batch_X - min_val) / (max_val - min_val)
    
    variance_to_keep = 0.95  #me quedo con el 95% de la varianza, esto es flexible (mientras más porcentaje, mayor va  quedar la dimensionalidad de mi X)

    pca = PCA()
    batch_X = pca.fit_transform(batch_X)  #aplico pca para los datos escalados

    #Encuentro el número mínimo de componentes principales para alcanzar la varianza deseada
    cumulative_variance_ratio = np.cumsum(pca.explained_variance_ratio_)
    #('n_components_to_keep' contendrá el número mínimo de componentes principales necesarios para explicar al menos el 95% de la varianza en los datos.)
    n_components_to_keep = np.argmax(cumulative_variance_ratio >= variance_to_keep) + 1 #chona me dijo que me deberían quedar por ejemplo 1000 atributos

    #Selecciono la cant de componentes principales que me salió
    batch_X = batch_X[:, :n_components_to_keep]
    
#//////NUEVO
    
    #agrego los scaleograms y labels a las listas X y y
    X.concatenate(batch_X)
    y.extend(labels)


#convierto X e y a formato .npy
X = np.concatenate(X, axis=0)
y = np.array(y)

print('Ya se separó todo!')
print('Salió todo bien, tranquina :))')'''

"#SEPARO EN X E Y\nX = []\ny = []\n\n#itero los lotes\nfor batch_data in batched_dataset:\n    paths = batch_data['path'].numpy()\n    labels = batch_data['label'].numpy()\n    \n    #cargo los scaleograms desde los archivos .npy\n    batch_X = []\n    for path in paths:\n        spectrogram = np.load(path.decode('utf-8'))\n        batch_X.append(spectrogram)\n    \n#//////NUEVO\n\n    #primero tengo que convertirlo en un archivo numpy porque sino no quiere\n    batch_X = np.array(batch_X)\n    \n    X_shape = batch_X.shape\n    shape_0 = X_shape[0]\n\n    # Aplanar\n    batch_X = batch_X.reshape(shape_0, -1)\n    \n    #NORMALIZO X en rango [-1, 1] para que el cero quede en el centro\n    min_val = np.min(batch_X)\n    max_val = np.max(batch_X)\n\n    X = -1 + 2 * (batch_X - min_val) / (max_val - min_val)\n    \n    variance_to_keep = 0.95  #me quedo con el 95% de la varianza, esto es flexible (mientras más porcentaje, mayor va  quedar la dimensionalidad de mi X)\n\n    pca = PCA()\n 

In [6]:
#bd_iter = iter(batched_dataset)
#batch_data = next(bd_iter)

In [7]:
#batch_data

{'grpno': <tf.Tensor: shape=(2,), dtype=int64, numpy=array([10, 10], dtype=int64)>,
 'label': <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0], dtype=int64)>,
 'path': <tf.Tensor: shape=(2,), dtype=string, numpy=
 array([b'C:\\Users\\47575909\\Desktop\\scaleogram\\subvideo_11/trial_0.npy',
        b'C:\\Users\\47575909\\Desktop\\scaleogram\\subvideo_11/trial_1.npy'],
       dtype=object)>}

In [12]:
'''
paths = batch_data['path'].numpy()
labels = batch_data['label'].numpy()
    
# Cargar los scaleograms desde los archivos .npy
batch_X = []
for path in paths:
    spectrogram = np.load(path.decode('utf-8'))
    batch_X.append(spectrogram)
    
batch_X = np.array(batch_X)
        
# batch_X = batch_X.reshape((batch_X.shape[0], -1))  # Aplanar los datos
    
# NORMALIZA X en rango [-1, 1] para que el cero quede en el centro
min_val = np.min(batch_X)
max_val = np.max(batch_X)
    
batch_X = -1 + 2 * (batch_X - min_val) / (max_val - min_val)

batch_X'''

array([[[[-0.99985725, -0.99985456, -0.9998539 , ..., -0.9989402 ,
          -0.9989198 , -0.9989116 ],
         [-0.9997775 , -0.9997736 , -0.99977314, ..., -0.9983727 ,
          -0.99833775, -0.998324  ],
         [-0.99966854, -0.99966335, -0.99966353, ..., -0.99761903,
          -0.9975616 , -0.99753934],
         ...,
         [-0.994659  , -0.9946357 , -0.99461246, ..., -0.9908578 ,
          -0.9908636 , -0.9908695 ],
         [-0.96086556, -0.9608654 , -0.96086526, ..., -0.9608342 ,
          -0.96083426, -0.9608343 ],
         [-0.87473947, -0.87473947, -0.87473947, ..., -0.8747394 ,
          -0.87473947, -0.87473947]],

        [[-0.99991345, -0.9999164 , -0.9999175 , ..., -0.999667  ,
          -0.9996697 , -0.9996768 ],
         [-0.99988097, -0.99988747, -0.99989027, ..., -0.9994956 ,
          -0.99949825, -0.9995087 ],
         [-0.99984705, -0.99986124, -0.99986786, ..., -0.99927205,
          -0.999273  , -0.9992872 ],
         ...,
         [-0.995192  , -0.9951628 

In [13]:
#batch_X[0].shape

(14, 230, 384)

In [10]:
#batch_X.shape, labels.shape

((2, 1236480), (2,))

In [36]:
#np.resize(batch_X[0], (3, 224, 224))

array([[[-0.99985725, -0.99985456, -0.9998539 , ..., -0.99991643,
         -0.99991775, -0.9999196 ],
        [-0.99992204, -0.999925  , -0.9999283 , ..., -0.9999353 ,
         -0.99993604, -0.9999361 ],
        [-0.9999355 , -0.9999346 , -0.9999341 , ..., -0.99990755,
         -0.9999017 , -0.9998941 ],
        ...,
        [-0.9664635 , -0.96722597, -0.9679918 , ..., -0.99134135,
         -0.99110097, -0.9908375 ],
        [-0.9905519 , -0.9902452 , -0.98991853, ..., -0.98797005,
         -0.988031  , -0.98809224],
        [-0.9881534 , -0.98821443, -0.9882751 , ..., -0.9532691 ,
         -0.9527509 , -0.9522377 ]],

       [[-0.9517298 , -0.9512274 , -0.95073086, ..., -0.9882792 ,
         -0.98808426, -0.98788995],
        [-0.98769647, -0.98750395, -0.9873127 , ..., -0.9355713 ,
         -0.935637  , -0.93570983],
        [-0.93578964, -0.9358762 , -0.93596923, ..., -0.9767152 ,
         -0.9765628 , -0.97640944],
        ...,
        [-0.9934355 , -0.9931943 , -0.9930401 , ..., -

In [32]:
#data_1d =  np.array([features_2d.flatten() for features_2d in batch_X[0]])
#data_1d.shape

(14, 88320)

In [8]:
# Define el número máximo de componentes principales que deseas mantener para todos los lotes
#max_components = 1000  # Puedes ajustar este valor según tus necesidades

X_list = []  # Lista temporal para X
y_list = []  # Lista temporal para y


In [9]:
# Crea un objeto tqdm para rastrear el progreso
pbar = tqdm(total=len(filenames))

# Itera los lotes
for batch_data in batched_dataset:
    paths = batch_data['path'].numpy()
    labels = batch_data['label'].numpy()
    
    # Cargar los scaleograms desde los archivos .npy
    batch_xs = []
    for path in paths:
        spectrogram = np.load(path.decode('utf-8'))
        batch_xs.append(spectrogram)  # Corregir el nombre de la variable aquí
    
    # Convierte batch_x en un arreglo NumPy
    batch_xs = np.array(batch_xs)

    for (batch_x, label) in zip(batch_xs, labels):

        amm = batch_x.shape[0] * batch_x.shape[1] * batch_x.shape[2]
    
        x_flat = batch_x.reshape(amm, -1).squeeze()
        (batch_x.shape[0], batch_x.shape[1], batch_x.shape[2]), x_flat.shape
    
        multiplier = 1
    
        while 224 * 224 * 3 * multiplier < amm:
            multiplier += 1
    
        # Creo un array de ceros de 244*244*3*multiplier, mas grande que mi input
        x_extended = np.zeros((224 * 224 * 3 * multiplier))
    
        # Relleno el array de ceros con mi input, me quedan ceros de relleno
        x_extended[:amm] = x_flat
    
        # Reshapeo
        x_big_2d = x_extended.reshape(224 * 224, 3 * multiplier)
        x_big_2d.shape
    
        pca = PCA(
            n_components=3,
        )
    
        pca.fit(x_big_2d)
    
        x_big_2d_reduced = pca.transform(x_big_2d)
    
        x_big_3d_reduced = x_big_2d_reduced.reshape(224, 224, 3)
        
        # Agrega los scaleograms y labels a X_list e y_list
        X_list.append(x_big_3d_reduced)
        y_list.append(label)
    
        print(pca.explained_variance_ratio_, np.sum(pca.explained_variance_ratio_))
    
    # Actualiza la barra de progreso
    pbar.update(len(paths))  # Actualiza la barra de progreso según la cantidad de archivos en el lote

# Convierte X_list e y_list en arreglos NumPy
X = np.array(X_list)
y = np.array(y_list)

# Cierra la barra de progreso
# pbar.close()



297it [02:19,  2.13it/s]                                                                         | 0/1 [00:00<?, ?it/s]

2it [00:00, 11.65it/s]                                                                                                 

[0.98447994 0.01027934 0.00236879] 0.9971280670765491
[0.98163964 0.01222149 0.00279338] 0.996654512124952
[0.9829829  0.01131234 0.00252343] 0.9968186713155835



4it [00:00, 11.01it/s]
6it [00:00, 11.47it/s]

[0.98880257 0.0072079  0.00176042] 0.9977708876183397
[0.9895006  0.0071196  0.00147605] 0.9980962539557829
[0.98774516 0.00847514 0.00169244] 0.9979127501547903



8it [00:00, 11.56it/s]

[0.97063787 0.02000034 0.00411281] 0.9947510283556888
[0.98889562 0.00768251 0.00156298] 0.9981411041675438
[0.98677467 0.00874402 0.00198778] 0.997506468045326



10it [00:00, 11.51it/s]

[0.99065987 0.00600047 0.00145978] 0.9981201174350035
[0.98706446 0.00859378 0.0019247 ] 0.997582944129573



12it [00:01, 11.13it/s]


[0.98165299 0.0123771  0.00293656] 0.9969666569305552
[0.97996873 0.01340858 0.00336244] 0.9967397534084106
[0.98378536 0.01044946 0.00273679] 0.9969716124290832


14it [00:01, 10.80it/s]
16it [00:01, 11.08it/s]

[0.99011579 0.00655354 0.00159714] 0.9982664725007893
[0.98804178 0.00793941 0.00196865] 0.9979498406619608
[0.98423531 0.0107212  0.00220329] 0.997159802004395



18it [00:01, 10.72it/s]


[9.92182246e-01 5.92604742e-03 8.35265447e-04] 0.9989435587106614
[0.98658993 0.0091466  0.00183553] 0.9975720549848738
[0.98920212 0.00709703 0.00170065] 0.9979997979691461


20it [00:01, 10.49it/s]
22it [00:02, 10.79it/s]

[0.98540262 0.01026838 0.00194412] 0.9976151140406908
[9.91187862e-01 6.65795030e-03 9.68762466e-04] 0.9988145752259933
[0.98259174 0.01200994 0.00234823] 0.9969499154683675



24it [00:02, 10.96it/s]


[0.9848308  0.01049556 0.00230984] 0.9976362061887665
[0.98028057 0.01355708 0.00309147] 0.9969291199149929
[0.98284969 0.01179047 0.00286069] 0.997500846214013


26it [00:02, 10.96it/s]
28it [00:02, 10.97it/s]

[0.98373716 0.01096651 0.00261608] 0.9973197464610895
[0.98268582 0.01163016 0.00275079] 0.9970667619412439
[0.98712846 0.00889491 0.00205961] 0.9980829777488934



30it [00:02, 10.61it/s]


[0.9844974  0.0106044  0.00248706] 0.9975888634489787
[0.98532261 0.00999013 0.00236671] 0.9976794456701292
[0.98752575 0.00843418 0.00185745] 0.9978173797995064


32it [00:02, 10.43it/s]
34it [00:03, 10.61it/s]

[0.98795749 0.00821434 0.00177402] 0.9979458534470437
[0.98423629 0.01056982 0.00256803] 0.9973741418048689
[0.98446316 0.0107592  0.00257168] 0.9977940362077227



36it [00:03, 10.68it/s]
38it [00:03, 10.87it/s]

[0.98231405 0.01205376 0.00288921] 0.9972570223043582
[0.976592   0.01621472 0.00383003] 0.9966367560831099
[0.97657831 0.01636369 0.00372148] 0.9966634771433833



40it [00:03, 11.15it/s]

[0.97006118 0.0202878  0.00490449] 0.9952534725403337
[0.98489459 0.01041603 0.0023543 ] 0.9976649244297947
[0.98521744 0.01014124 0.00218408] 0.9975427607198047



42it [00:03, 11.10it/s]
44it [00:04, 11.38it/s]

[0.98827749 0.00821757 0.00173851] 0.9982335647310678
[0.98508576 0.00997838 0.00230287] 0.997367013365564
[0.97985439 0.01331712 0.00334323] 0.996514741498147



46it [00:04, 11.45it/s]

[0.98557502 0.01007103 0.00225785] 0.9979039043471946
[0.98204499 0.01227288 0.00276233] 0.9970801966478897
[0.98094184 0.01305623 0.00301257] 0.9970106380620632



48it [00:04, 11.32it/s]
50it [00:04, 11.57it/s]

[0.98401707 0.01112168 0.00260833] 0.9977470790807846
[0.98018965 0.01359957 0.00323617] 0.9970253899222896
[0.97893722 0.01464561 0.0033479 ] 0.9969307253153205



52it [00:04, 11.25it/s]

[0.97931105 0.01457437 0.00324146] 0.9971268783690165
[0.97832686 0.01483613 0.00349767] 0.9966606640321839
[0.97802977 0.01551535 0.00349957] 0.9970446903570872



54it [00:04, 11.16it/s]
56it [00:05, 11.40it/s]

[0.97412761 0.0180203  0.00421668] 0.9963645859027253
[0.97902544 0.01478324 0.00311295] 0.9969216334274945
[0.98347187 0.01165785 0.00238914] 0.9975188646213008



58it [00:05, 11.31it/s]

[0.98253194 0.01204919 0.00273819] 0.9973193234289298
[0.96644294 0.02370485 0.00557109] 0.9957188740186572
[0.97935741 0.01348944 0.00324442] 0.9960912724605763



60it [00:05, 11.10it/s]

[0.99101873 0.00593282 0.00139049] 0.9983420499300152
[0.9887262  0.00739669 0.00184558] 0.9979684689953744
[0.98157113 0.0119066  0.0032301 ] 0.9967078187964316



62it [00:05, 10.73it/s]
64it [00:05, 10.84it/s]

[0.98102036 0.01288238 0.00315055] 0.9970532958711198
[0.98071694 0.01359485 0.00305287] 0.9973646652180478
[0.97287906 0.01896558 0.00427512] 0.9961197648338456



66it [00:05, 11.15it/s]


[0.9860651  0.00939067 0.00237581] 0.9978315727142922
[0.98811475 0.00803197 0.00212715] 0.9982738738274485
[0.98882049 0.00742005 0.00181971] 0.9980602463695822


68it [00:06, 11.05it/s]
70it [00:06, 10.70it/s]

[0.98639344 0.00896933 0.00252032] 0.9978830891394564
[0.98196389 0.01224267 0.00304221] 0.9972487781537531



72it [00:06, 10.49it/s]

[0.97967783 0.01378467 0.00353418] 0.9969966836717253
[0.97336593 0.01848219 0.00445094] 0.996299059979888



74it [00:06, 10.64it/s]

[0.96213529 0.02755327 0.00621431] 0.9959028713397112
[0.96541585 0.02481727 0.00569879] 0.9959319115499721
[0.97033941 0.01997315 0.00528046] 0.9955930186827098



76it [00:06, 10.66it/s]


[0.97231431 0.01900327 0.00472757] 0.9960451488208343
[0.97955597 0.01395564 0.00342951] 0.9969411222661356
[0.98333223 0.01155642 0.00281033] 0.9976989727994399


78it [00:07, 10.80it/s]
80it [00:07, 10.98it/s]

[0.97993591 0.01383763 0.00323751] 0.9970110467534996
[0.97892971 0.01475547 0.00347114] 0.9971563188524277
[0.98375061 0.01128628 0.00267569] 0.9977125768944091



82it [00:07, 11.23it/s]
84it [00:07, 11.46it/s]

[0.98565326 0.00986793 0.00240176] 0.9979229420218406
[0.985051   0.01003739 0.00266001] 0.9977484090529068
[0.97691779 0.01570424 0.00402979] 0.9966518267628461



86it [00:07, 11.65it/s]

[0.97707939 0.01578922 0.00386605] 0.9967346548628273
[0.98394181 0.01111885 0.0026419 ] 0.9977025648522101
[0.98510603 0.01042563 0.00230716] 0.9978388314955151



88it [00:07, 11.78it/s]


[0.98312386 0.01158018 0.00265925] 0.9973632885369615
[0.98663895 0.00915324 0.00219112] 0.9979833124894503
[0.98448122 0.01041071 0.00260877] 0.9975006941165554


90it [00:08, 11.28it/s]
92it [00:08, 10.87it/s]

[0.98274552 0.01175528 0.00286578] 0.9973665741843266
[0.98111817 0.01311057 0.00315395] 0.9973826874861789
[0.98332962 0.01160798 0.00269207] 0.9976296664997196



94it [00:08, 10.60it/s]


[0.98178395 0.01275374 0.00297276] 0.997510449636777
[0.9808777  0.01336964 0.00312042] 0.9973677629751329
[0.98008727 0.01396083 0.00322617] 0.9972742654334776


96it [00:08, 10.41it/s]
98it [00:08, 10.37it/s]

[0.98562648 0.00984201 0.00240403] 0.997872533005803
[0.98297905 0.01166761 0.00293386] 0.997580518426271
[0.98145327 0.01263847 0.00306166] 0.9971534016608863



100it [00:09, 10.42it/s]


[0.98484877 0.01044091 0.00248773] 0.9977774021431791
[0.98212667 0.01232556 0.00293494] 0.9973871635607141
[0.97934432 0.01421825 0.0034043 ] 0.9969668749257395


102it [00:09, 10.35it/s]
104it [00:09, 10.91it/s]

[0.97981535 0.01429167 0.00315206] 0.9972590830773335
[0.98772572 0.00867014 0.00188727] 0.9982831239363819
[0.98738806 0.00863487 0.00201311] 0.9980360379148663



106it [00:09, 11.08it/s]
108it [00:09, 11.22it/s]

[0.9802039  0.01312379 0.00332439] 0.9966520803984832
[0.9817374  0.01251597 0.00307413] 0.9973274920284412
[0.9750792  0.01679173 0.00421335] 0.9960842869097111



110it [00:10, 11.34it/s]

[0.9850132  0.01027132 0.00250473] 0.9977892426646364
[0.98612363 0.00939674 0.00228183] 0.9978022032599099
[0.98555575 0.00999528 0.00231934] 0.9978703677566716



112it [00:10, 11.40it/s]
114it [00:10, 11.54it/s]

[0.96902565 0.02086264 0.00496009] 0.9948483770110924
[0.99226682 0.00488098 0.0013626 ] 0.9985103975518625
[0.99401408 0.00365904 0.00113417] 0.9988072868522393



116it [00:10, 11.40it/s]

[0.99187736 0.00539237 0.00133956] 0.9986092841158462
[0.98634781 0.00918684 0.00231651] 0.9978511603002959
[0.97563417 0.01732587 0.00399339] 0.9969534288385143



118it [00:10, 11.59it/s]
120it [00:10, 11.82it/s]

[0.97470929 0.01799592 0.00387844] 0.9965836498856652
[0.97588145 0.01568896 0.0037716 ] 0.9953420092810829
[0.99315267 0.00437741 0.0012618 ] 0.9987918845562409



122it [00:11, 11.73it/s]

[0.99189062 0.00520144 0.00134194] 0.9984340112073281
[0.98507479 0.00993957 0.00277789] 0.9977922488033584
[0.98423959 0.01026571 0.00287014] 0.9973754384630081



124it [00:11, 11.51it/s]
126it [00:11, 11.83it/s]

[0.98572635 0.00917576 0.002456  ] 0.9973581070790254
[0.98711803 0.00850213 0.00227101] 0.9978911637783779
[0.98263338 0.01167843 0.00295979] 0.9972716015968206



128it [00:11, 11.73it/s]

[0.97682099 0.0155637  0.00397516] 0.996359849915342
[9.94178920e-01 3.90918407e-03 8.55313615e-04] 0.9989434176270422
[9.94355512e-01 3.73444515e-03 9.22000931e-04] 0.9990119583975509



130it [00:11, 11.49it/s]
132it [00:11, 11.76it/s]

[0.98213152 0.01161165 0.00279323] 0.996536395312689
[0.98555878 0.00966768 0.00218908] 0.9974155418855937
[0.98995977 0.00708006 0.00141762] 0.9984574483107813



134it [00:12, 11.61it/s]

[0.98474343 0.01045479 0.0021252 ] 0.9973234209840445
[9.91956095e-01 6.15740645e-03 8.84802289e-04] 0.9989983039603993
[0.98639941 0.00968717 0.00178666] 0.997873240370714



136it [00:12, 11.92it/s]
138it [00:12, 11.97it/s]

[0.9861444  0.00990409 0.00198654] 0.9980350260348634
[0.9839759  0.01139131 0.00226454] 0.9976317417960439
[0.97511207 0.01747301 0.00396618] 0.9965512584519507



140it [00:12, 11.96it/s]

[0.97881339 0.0147376  0.00345034] 0.9970013344156226
[0.97877843 0.01427615 0.00372184] 0.9967764243312106
[0.97750751 0.01614139 0.0033914 ] 0.9970402928512031



142it [00:12, 11.97it/s]
144it [00:12, 12.00it/s]

[0.98221304 0.01306292 0.00265356] 0.9979295113459298
[0.97548855 0.01685714 0.00393988] 0.9962855729269757
[0.97519211 0.017272   0.0043095 ] 0.996773610541002



146it [00:13, 12.19it/s]

[0.97038811 0.02074324 0.00507694] 0.9962082880888421
[0.96339523 0.02628241 0.00575577] 0.995433420429248
[0.96352635 0.02683269 0.00557911] 0.9959381431090644



148it [00:13, 11.95it/s]
150it [00:13, 11.99it/s]

[0.95651177 0.03193121 0.00656375] 0.9950067343274839
[0.98465088 0.01085542 0.00234339] 0.9978496853810549
[0.98656366 0.00941003 0.00214569] 0.998119384076045



152it [00:13, 11.97it/s]

[0.97459522 0.01693831 0.00411206] 0.9956455858034281
[0.96001824 0.02816195 0.00686467] 0.9950448600157411
[0.96847389 0.02198639 0.00532446] 0.9957847367211939



154it [00:13, 12.00it/s]
156it [00:13, 12.35it/s]

[0.97238558 0.0191594  0.00454668] 0.9960916658348072
[0.97031086 0.02113312 0.0048505 ] 0.9962944812216378
[0.96984992 0.02123007 0.00500834] 0.9960883352906377



158it [00:14, 12.06it/s]

[0.96443953 0.02483153 0.00616334] 0.9954343917439787
[0.97450365 0.01788168 0.00430217] 0.9966875001446475
[0.97266816 0.01896795 0.00480741] 0.9964435240105336



160it [00:14, 11.86it/s]
162it [00:14, 11.93it/s]

[0.96948463 0.02160331 0.00487655] 0.9959644823103407
[0.97538564 0.01774516 0.00391899] 0.9970497892896164
[0.97384761 0.01884226 0.00408959] 0.9967794626125703



164it [00:14, 11.93it/s]

[0.96684031 0.02320651 0.00578308] 0.9958299095897374
[0.96350215 0.02535757 0.00651745] 0.9953771786298518
[0.95982782 0.02823225 0.0073089 ] 0.9953689688938687



166it [00:14, 11.95it/s]
168it [00:14, 11.97it/s]

[0.96302007 0.02582179 0.00657975] 0.9954216062508867
[0.97118236 0.02004461 0.00496732] 0.9961942902746573
[0.97130738 0.01999435 0.00499125] 0.9962929769434645



170it [00:15, 12.16it/s]

[0.96877965 0.02210671 0.00522195] 0.9961083151138413
[0.96205777 0.0266129  0.00638397] 0.9950546347275288
[0.96352204 0.0260841  0.00603705] 0.9956431851745586



172it [00:15, 11.93it/s]
174it [00:15, 11.95it/s]

[0.96240901 0.02674118 0.00640404] 0.9955542215026233
[0.96241123 0.02568005 0.00676302] 0.9948543046700675
[0.9735911  0.01797945 0.00464298] 0.9962135327715592



176it [00:15, 11.95it/s]

[0.97780471 0.01535116 0.00390207] 0.9970579306521641
[0.97258994 0.0190293  0.0046857 ] 0.9963049451080882
[0.9696798  0.02148388 0.00505236] 0.996216032116595



178it [00:15, 11.99it/s]
180it [00:15, 11.98it/s]

[0.97424066 0.01802351 0.0042344 ] 0.9964985618295955
[0.97626764 0.0166561  0.0038891 ] 0.9968128362816028
[0.97396782 0.01789775 0.00439447] 0.9962600392537624



182it [00:16, 11.84it/s]

[0.97136668 0.02052141 0.00475985] 0.9966479395323501
[0.96932865 0.02170519 0.00516123] 0.9961950770928522
[0.96605175 0.02400013 0.0057794 ] 0.9958312831871607



184it [00:16, 11.72it/s]
186it [00:16, 12.14it/s]

[0.97370162 0.01854037 0.00446145] 0.9967034377097884
[0.97598135 0.01687627 0.00402284] 0.99688046601666
[0.97672894 0.01621632 0.00389564] 0.9968408902840905



188it [00:16, 12.07it/s]

[0.96961073 0.02154346 0.00518452] 0.9963387105416096
[0.96780986 0.02263271 0.00525677] 0.9956993451429259
[0.96521643 0.02537528 0.00547756] 0.9960692679491342



190it [00:16, 11.72it/s]
192it [00:16, 12.17it/s]

[0.95901882 0.02994299 0.00641795] 0.995379767315558
[0.951392   0.03519059 0.00781018] 0.994392768290839
[0.95335342 0.03410871 0.00744442] 0.9949065517624671



194it [00:17, 11.95it/s]

[0.95438804 0.03320923 0.00735479] 0.9949520662750208
[0.95733335 0.03085184 0.00677077] 0.9949559558482696
[0.95919923 0.02942792 0.00656782] 0.9951949734098232



196it [00:17, 12.13it/s]
198it [00:17, 11.76it/s]

[0.95826172 0.03047837 0.00665059] 0.9953906778510161
[0.97390091 0.01836436 0.00411169] 0.9963769603432169
[0.98244189 0.01248483 0.00285586] 0.9977825740352002



200it [00:17, 11.80it/s]

[0.98165879 0.01284059 0.00305139] 0.997550763439061
[0.97145571 0.02028162 0.00445878] 0.996196109768765
[0.96912248 0.02279209 0.00455267] 0.9964672400872453



202it [00:17, 11.89it/s]
204it [00:17, 11.92it/s]

[0.96778842 0.02379057 0.00475341] 0.9963323989765837
[0.96889798 0.02227588 0.00485739] 0.9960312493191084
[0.9744771  0.01808856 0.00414899] 0.9967146415628073



206it [00:18, 12.12it/s]

[0.97201092 0.01951139 0.00453677] 0.9960590828784891
[0.96257235 0.0261006  0.00627393] 0.9949468935502309
[0.96055901 0.02863228 0.00624092] 0.995432211500554



208it [00:18, 11.91it/s]
210it [00:18, 11.94it/s]

[0.96008668 0.02977001 0.00607401] 0.9959307069206076
[0.96046268 0.02838036 0.0062324 ] 0.9950754454980322
[0.96962368 0.02182503 0.00484925] 0.9962979685848504



212it [00:18, 11.94it/s]

[0.97137452 0.02076822 0.00440216] 0.9965448993665305
[0.96260962 0.02634344 0.0058249 ] 0.9947779665751609
[0.9870837  0.00911278 0.00171335] 0.9979098360611467



214it [00:18, 11.95it/s]
216it [00:18, 11.99it/s]

[0.98983532 0.00710595 0.00165198] 0.9985932491899312
[0.98698583 0.00874527 0.00198089] 0.9977119771226263
[0.98502419 0.01077212 0.00189292] 0.9976892343014834



218it [00:19, 12.18it/s]

[0.98377947 0.01171981 0.00220505] 0.9977043215864267
[0.98143236 0.01257085 0.00272565] 0.9967288597375092
[0.9911405  0.00664834 0.00107426] 0.9988630938708666



220it [00:19, 12.29it/s]
222it [00:19, 12.20it/s]

[0.98847401 0.00805419 0.00165471] 0.9981829102396418
[0.98869717 0.00757408 0.00195746] 0.9982287113365799
[0.98241021 0.0124705  0.00271466] 0.997595372355909



224it [00:19, 11.78it/s]

[0.96797382 0.02292185 0.00517441] 0.9960700852161155
[0.96254357 0.02699689 0.0061345 ] 0.9956749524053428
[0.95890412 0.02901129 0.00692819] 0.9948435930923079



226it [00:19, 11.87it/s]
228it [00:19, 11.91it/s]

[0.96089478 0.02848233 0.00636312] 0.9957402224230044
[0.96231977 0.02735182 0.00615181] 0.9958234017734322
[0.95799867 0.02996741 0.00669415] 0.9946602263121139



230it [00:20, 12.12it/s]

[0.96360543 0.02667577 0.00572019] 0.9960013886022958
[0.96581486 0.02497919 0.00540391] 0.9961979559817926
[0.96301754 0.02642532 0.00591786] 0.9953607118889992



232it [00:20, 11.88it/s]
234it [00:20, 11.94it/s]

[0.96602574 0.02452243 0.00531061] 0.995858778689343
[0.96117745 0.02851029 0.00613757] 0.9958253123274716
[0.9616031  0.02765757 0.00622346] 0.9954841365844211



236it [00:20, 12.28it/s]

[0.96108474 0.02806076 0.00619163] 0.9953371214643872
[0.97873847 0.01426199 0.00325047] 0.9962509342740012
[0.98962588 0.00733283 0.00156009] 0.9985188032648623



238it [00:20, 11.84it/s]
240it [00:20, 11.93it/s]

[0.98642488 0.00964172 0.00189007] 0.9979566659957727
[0.97486552 0.01785168 0.0039774 ] 0.9966946041866374
[0.97499804 0.01769764 0.00406455] 0.9967602275245886



242it [00:21, 12.13it/s]

[0.96845019 0.0225389  0.00486737] 0.9958564574678008
[0.96677684 0.02431281 0.0050765 ] 0.9961661443381802
[0.96675507 0.02461134 0.00494393] 0.9963103380779686



244it [00:21, 11.91it/s]
246it [00:21, 11.92it/s]

[0.96292927 0.02663528 0.00584312] 0.9954076691602104
[0.96256828 0.02716303 0.00596836] 0.9956996659936542
[0.96743752 0.02324596 0.0053515 ] 0.9960349835988338



248it [00:21, 11.94it/s]

[0.97187067 0.02013132 0.00461876] 0.996620749861333
[0.96560219 0.0244611  0.00557689] 0.9956401783648863
[0.96844238 0.02266945 0.00504276] 0.9961545951811528



250it [00:21, 11.99it/s]
252it [00:21, 11.99it/s]

[0.98254594 0.01202788 0.00277508] 0.9973488986928801
[0.98550535 0.0098888  0.00232951] 0.9977236569628793
[0.97798488 0.01476697 0.00351642] 0.9962682723017975



254it [00:22, 11.84it/s]

[0.97005488 0.02084903 0.00501026] 0.9959141691451753
[0.96987408 0.02112841 0.00509169] 0.9960941897974355
[0.96800251 0.02272619 0.00542654] 0.9961552390232494



256it [00:22, 12.02it/s]
258it [00:22, 12.01it/s]

[0.96704101 0.02312178 0.00564502] 0.9958078089801953
[0.96249875 0.02681812 0.00635214] 0.9956690056904809
[0.95995286 0.02870717 0.00673766] 0.9953976817898512



260it [00:22, 11.99it/s]

[0.9553818  0.03164721 0.00759885] 0.9946278614094465
[0.95674213 0.03106659 0.00714358] 0.9949522981284464
[0.96512943 0.02527587 0.00568273] 0.9960880317200611



262it [00:22, 11.99it/s]
264it [00:22, 12.02it/s]

[0.96985985 0.02203555 0.00464506] 0.9965404532581185
[0.96643731 0.02369706 0.0053806 ] 0.9955149686070567
[0.95857862 0.02991289 0.00670102] 0.9951925247284339



266it [00:23, 11.88it/s]

[0.94873552 0.03701644 0.00836097] 0.9941129335396617
[0.95971843 0.02902658 0.00645259] 0.9951975995816961
[0.96613911 0.0241907  0.00535803] 0.9956878418840298



268it [00:23, 12.05it/s]
270it [00:23, 12.04it/s]

[0.97002457 0.02184841 0.00464048] 0.9965134688144618
[0.97353601 0.01901066 0.00405992] 0.9966065828688286
[0.97740694 0.01627335 0.00351669] 0.9971969794484549



272it [00:23, 12.00it/s]

[0.97631157 0.01643788 0.00392372] 0.9966731702271315
[0.96807427 0.02225674 0.0053083 ] 0.995639305035703
[0.95944549 0.02854702 0.00655524] 0.9945477558257498



274it [00:23, 12.03it/s]
276it [00:23, 12.02it/s]

[0.9645157  0.02657985 0.00538853] 0.9964840782183847
[0.96833735 0.02292998 0.00496009] 0.9962274187108219
[0.96548232 0.02458802 0.00550777] 0.9955781189802668



278it [00:24, 11.88it/s]

[0.97025215 0.02106212 0.00462171] 0.9959359723905125
[0.96950107 0.02201484 0.00455859] 0.9960745058817689
[0.9711528  0.02059173 0.00441722] 0.9961617413938736



280it [00:24, 11.72it/s]
282it [00:24, 11.80it/s]

[0.96986032 0.0208124  0.00498678] 0.9956594958559527
[0.96848562 0.02178997 0.0051901 ] 0.9954656947633618
[0.973508   0.01910145 0.00425444] 0.9968638821953664



284it [00:24, 11.84it/s]

[0.97471106 0.01766525 0.00407162] 0.9964479255826316
[0.97751045 0.015955   0.00352135] 0.9969867976097504
[0.97363358 0.01924509 0.0038703 ] 0.9967489694208983



286it [00:24, 11.89it/s]
288it [00:24, 11.95it/s]

[0.96763937 0.02366288 0.00494188] 0.9962441299099515
[0.96297528 0.02632137 0.00591407] 0.9952107180503662
[0.96838423 0.02292088 0.00504505] 0.9963501685039053



290it [00:25, 11.83it/s]

[0.96559697 0.02419481 0.00570908] 0.9955008556704511
[0.97103892 0.02022528 0.00493468] 0.9961988852680387
[0.97453866 0.01806498 0.00393305] 0.9965366850888913



292it [00:25, 11.99it/s]
294it [00:25, 12.00it/s]

[0.97560077 0.01711507 0.00389387] 0.9966097117035042
[0.97391968 0.01830009 0.00405659] 0.9962763572444442
[0.97265133 0.01942743 0.00424961] 0.9963283698348192



296it [00:25, 11.98it/s]

[0.97179023 0.0200362  0.00451961] 0.9963460303814681
[0.97059032 0.02084053 0.00466662] 0.99609745960426
[0.97275042 0.01934273 0.0044835 ] 0.9965766454401527



298it [00:25, 12.01it/s]

[0.97617441 0.01656554 0.00402867] 0.9967686150402755
[0.97932399 0.01410182 0.00341593] 0.9968417425795524


In [8]:
X.shape, y.shape

((1790, 3, 244, 244), (1790,))

In [34]:
'''variance_to_keep = 0.95  # Me quedo con el 95% de la varianza
n_components = 14
pca = PCA(n_components=n_components)

data_reduced = pca.fit_transform(data_1d)
data_1d.shape, data_reduced.shape'''

((14, 88320), (14, 14))

In [4]:
'''VIEJO BUENO
# Crea un objeto tqdm para rastrear el progreso
pbar = tqdm(total=len(filenames))

# Itera los lotes
for batch_data in batched_dataset:
    paths = batch_data['path'].numpy()
    labels = batch_data['label'].numpy()
    
    # Cargar los scaleograms desde los archivos .npy
    batch_X = []
    for path in paths:
        spectrogram = np.load(path.decode('utf-8'))
        batch_X.append(spectrogram)
    
    # Convierte batch_X en un arreglo NumPy
    batch_X = np.array(batch_X)
    
    batch_X = batch_X.reshape((batch_X.shape[0], -1))  # Aplanar los datos
    
    # NORMALIZA X en rango [-1, 1] para que el cero quede en el centro
    min_val = np.min(batch_X)
    max_val = np.max(batch_X)

    batch_X = -1 + 2 * (batch_X - min_val) / (max_val - min_val)
    
    variance_to_keep = 0.95  # Me quedo con el 95% de la varianza
    n_components = 3
    pca = PCA(n_components=n_components)
    batch_X = pca.fit_transform(batch_X)  # Aplica PCA para los datos escalados
    

    # Asegúrate de que todos los lotes tengan la misma cantidad de componentes principales
    n_components_to_keep = min(max_components, batch_X.shape[1])
    if batch_X.shape[1] < max_components:
        # Rellena con ceros las columnas faltantes si es necesario
        zeros_to_add = max_components - batch_X.shape[1]
        zeros = np.zeros((batch_X.shape[0], zeros_to_add))
        batch_X = np.hstack((batch_X, zeros))
    else:
        batch_X = batch_X[:, :n_components_to_keep]

    # Agrega los scaleograms y labels a X_list e y_list
    X_list.append(batch_X)
    y_list.extend(labels)

    # Actualiza la barra de progreso
    pbar.update(len(paths))  # Actualiza la barra de progreso según la cantidad de archivos en el lote

# Convierte X_list e y_list en arreglos NumPy
X = np.concatenate(X_list, axis=0)
y = np.array(y_list)

# Cierra la barra de progreso
pbar.close()'''

12488it [05:03, 34.58it/s]                                                                                             

MemoryError: Unable to allocate 9.43 MiB for an array with shape (2, 1236480) and data type float32

In [10]:
#LOS GUARDO EN MI COMPUTADORA
#np.save('X.npy', X) está guardada normalizada en rango [0, 1], habría que cambiar eso
np.save('X_predict_epilepsy.npy', X)
#np.save('y_predict_normal.npy', y)


299it [00:40, 12.01it/s]

In [6]:
X_shape = X.shape
shape_0 = X_shape[0]
X_shape

(29588, 1000)

In [7]:
# Aplanar tus datos
X = X.reshape(shape_0, -1)

In [8]:
#NORMALIZO X en rango [-1, 1] para que el cero quede en el centro
min_val = np.min(X)
max_val = np.max(X)

X = -1 + 2 * (X - min_val) / (max_val - min_val)

#X = (X - X.min()) / (X.max() - X.min()) [0, 1]

In [9]:
X.shape

(29588, 1000)

In [10]:
'''from sklearn.decomposition import PCA

variance_to_keep = 0.95  #me quedo con el 95% de la varianza, esto es flexible (mientras más porcentaje, mayor va  quedar la dimensionalidad de mi X)

pca = PCA()
X = pca.fit_transform(X)  #aplico pca para los datos escalados

#Encuentro el número mínimo de componentes principales para alcanzar la varianza deseada
cumulative_variance_ratio = np.cumsum(pca.explained_variance_ratio_)
#('n_components_to_keep' contendrá el número mínimo de componentes principales necesarios para explicar al menos el 95% de la varianza en los datos.)
n_components_to_keep = np.argmax(cumulative_variance_ratio >= variance_to_keep) + 1 #chona me dijo que me deberían quedar por ejemplo 1000 atributos

#Selecciono la cant de componentes principales que me salió
X = X[:, :n_components_to_keep]'''

"from sklearn.decomposition import PCA\n\nvariance_to_keep = 0.95  #me quedo con el 95% de la varianza, esto es flexible (mientras más porcentaje, mayor va  quedar la dimensionalidad de mi X)\n\npca = PCA()\nX = pca.fit_transform(X)  #aplico pca para los datos escalados\n\n#Encuentro el número mínimo de componentes principales para alcanzar la varianza deseada\ncumulative_variance_ratio = np.cumsum(pca.explained_variance_ratio_)\n#('n_components_to_keep' contendrá el número mínimo de componentes principales necesarios para explicar al menos el 95% de la varianza en los datos.)\nn_components_to_keep = np.argmax(cumulative_variance_ratio >= variance_to_keep) + 1 #chona me dijo que me deberían quedar por ejemplo 1000 atributos\n\n#Selecciono la cant de componentes principales que me salió\nX = X[:, :n_components_to_keep]"

In [11]:
'''print("Me quedé con " + str(n_components_to_keep) + " componentes principales")
X.shape'''

'print("Me quedé con " + str(n_components_to_keep) + " componentes principales")\nX.shape'

In [12]:
'''print("Varianza explicada por cada componente principal:", pca.explained_variance_ratio_)'''

'print("Varianza explicada por cada componente principal:", pca.explained_variance_ratio_)'

In [ ]:
#no se si lo que hice está bien, chona me dijo que usara PaCMAP pero no lo entiendo, y acá encontre que con sklearn medio que se puede hacer asi que :)

In [ ]:
#hago una función?